ALTER TABLE repositories
    ADD COLUMN IF NOT EXISTS is_fork    BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS fork_of_id BIGINT  REFERENCES repositories(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS fork_count INTEGER NOT NULL DEFAULT 0;
CREATE INDEX IF NOT EXISTS idx_repos_fork_of ON repositories(fork_of_id);
