ALTER TABLE issues
    ADD COLUMN IF NOT EXISTS is_pinned  BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS is_locked  BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS locked_at  TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS idx_issues_pinned ON issues(repo_id, is_pinned) WHERE is_pinned = TRUE;
