ALTER TABLE repositories
    ADD COLUMN IF NOT EXISTS allow_issues      BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS allow_discussions BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS allow_projects    BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS allow_wiki        BOOLEAN NOT NULL DEFAULT TRUE;
