ALTER TABLE users
    ADD COLUMN IF NOT EXISTS name     TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS company  TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS location TEXT NOT NULL DEFAULT '';
