ALTER TABLE organizations
    ADD COLUMN IF NOT EXISTS website       TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS location      TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS contact_email TEXT NOT NULL DEFAULT '';
