// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comments.sql

package db

import (
	"context"
	"database/sql"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments (repo_id, issue_id, pull_id, author_id, author_name, body)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, repo_id, issue_id, pull_id, author_id, author_name, body, created_at, updated_at
`

type CreateCommentParams struct {
	RepoID     int64         `json:"repo_id"`
	IssueID    sql.NullInt64 `json:"issue_id"`
	PullID     sql.NullInt64 `json:"pull_id"`
	AuthorID   int64         `json:"author_id"`
	AuthorName string        `json:"author_name"`
	Body       string        `json:"body"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRowContext(ctx, createComment,
		arg.RepoID,
		arg.IssueID,
		arg.PullID,
		arg.AuthorID,
		arg.AuthorName,
		arg.Body,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.IssueID,
		&i.PullID,
		&i.AuthorID,
		&i.AuthorName,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comments WHERE id = $1
`

func (q *Queries) DeleteComment(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteComment, id)
	return err
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT c.id, c.repo_id, c.issue_id, c.pull_id, c.author_id, u.username AS author_name, c.body, c.created_at, c.updated_at
FROM comments c
JOIN users u ON c.author_id = u.id
WHERE c.id = $1
`

func (q *Queries) GetCommentByID(ctx context.Context, id int64) (Comment, error) {
	row := q.db.QueryRowContext(ctx, getCommentByID, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.IssueID,
		&i.PullID,
		&i.AuthorID,
		&i.AuthorName,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateComment = `-- name: UpdateComment :one
UPDATE comments SET body = $2, updated_at = NOW() WHERE id = $1
RETURNING id, repo_id, issue_id, pull_id, author_id, author_name, body, created_at, updated_at
`

func (q *Queries) UpdateComment(ctx context.Context, id int64, body string) (Comment, error) {
	row := q.db.QueryRowContext(ctx, updateComment, id, body)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.IssueID,
		&i.PullID,
		&i.AuthorID,
		&i.AuthorName,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCommentsByIssue = `-- name: ListCommentsByIssue :many
SELECT c.id, c.repo_id, c.issue_id, c.pull_id, c.author_id, u.username AS author_name, c.body, c.created_at, c.updated_at
FROM comments c
JOIN users u ON c.author_id = u.id
WHERE c.issue_id = $1
ORDER BY c.created_at ASC
`

func (q *Queries) ListCommentsByIssue(ctx context.Context, issueID sql.NullInt64) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, listCommentsByIssue, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comment{}
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.IssueID,
			&i.PullID,
			&i.AuthorID,
			&i.AuthorName,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommentsByPull = `-- name: ListCommentsByPull :many
SELECT c.id, c.repo_id, c.issue_id, c.pull_id, c.author_id, u.username AS author_name, c.body, c.created_at, c.updated_at
FROM comments c
JOIN users u ON c.author_id = u.id
WHERE c.pull_id = $1
ORDER BY c.created_at ASC
`

func (q *Queries) ListCommentsByPull(ctx context.Context, pullID sql.NullInt64) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, listCommentsByPull, pullID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comment{}
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.IssueID,
			&i.PullID,
			&i.AuthorID,
			&i.AuthorName,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
